use_gpu: True
device: 0
early_stop:
  patience: 10
federate:
  mode: standalone
  client_num: 1
  total_round_num: 3
  save_to: "llama.gsm8k.ckpt"
  make_global_eval: True
data:
  root: data/
  type: 'gsm8k@llm'
  splits: [0.98,0.01,0.01]
  splitter: 'iid'
llm:
  tok_len: 1000
  chat:
    max_len: 2000
  adapter:
    use: True
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'lora', 'r': 8, 'lora_alpha': 16, 'lora_dropout': 0.05 } ]
dataloader:
  batch_size: 1
model:
  type: '/data1/yfman/hf_models/Llama-2-7b-hf@huggingface_llm'
train:
  local_update_steps: 30
  batch_or_epoch: batch
  optimizer:
    lr: 0.0003
    weight_decay: 0.0
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmtrainer
eval:
  freq: 1
  metrics: ['loss', 'acc']
  count_flops: False