use_gpu: True
device: 7
early_stop:
  patience: 10
federate:
  mode: standalone
  client_num: 2
  sample_client_rate: 1.0
  total_round_num: 10
  save_to: "llama.dolly.offsite_tuning.ckpt"
  share_local_model: False
  online_aggr: False
data:
  root: data/
  type: 'dolly-15k@llm'
  splits: [0.98,0.01,0.01]
  splitter: 'lda'
  splitter_args: [{'alpha': 0.05}]
llm:
  tok_len: 1000
  chat:
    max_len: 1000
  offsite_tuning:
    use: True
    emu_l: 2
    emu_r: 30
dataloader:
  batch_size: 1
model:
  type: '/data1/yfman/hf_models/Llama-2-7b-hf@huggingface_llm'
train:
  local_update_steps: 10
  batch_or_epoch: batch
  optimizer:
    lr: 0.0001
    weight_decay: 0.0
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmtrainer
eval:
  freq: 1
  metrics: ['loss', 'acc']
  report: ['avg', 'weighted_avg']
  best_res_update_round_wise_key: 'val_loss'